name: Example Workflow

on:
  workflow_dispatch:
  push:
    branches: 
      - '**'
      - '!main'


jobs:
  Dags:
    runs-on: ubuntu-latest

    outputs:
      dockerfile-to-be-build: ${{ steps.step-one.outputs.dockerfile-to-be-build }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Step One
        id: step-one
        run: |
          # Your commands for step one here
          echo "::set-output name=dockerfile-to-be-build::$(git diff --name-only origin/main ${{ github.sha }} )"

  step-two:
    needs: Dags
    runs-on: ubuntu-latest
    if: contains(needs.step-one.outputs.dockerfile-to-be-build, '.')
    steps:
      - name: Step Two
        run: |
          # Use the output from step one here
          echo "Output from step one: ${{ needs.step-one.outputs.dockerfile-to-be-build }}"






# name: DEV Deploy

# env:
#   JSON: ${{ toJSON(github) }}
# on:
#   workflow_dispatch:
#   push:
#     branches: 
#       - '**'
#       - '!main'

# jobs:

  
#   Dags:
#     name: 'Dags/Sync'

#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

        
#       - name: sync to s3
#         run: |
#           echo dev branch name ${{ github.event.ref }}
#           echo github "${{ env.JSON }}" || true

          