name: Echo Opened PRs

on:
  push:
    branches:
        - "**"
        
jobs:
  echo-pr-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Echo PR branch names
        run: |
          echo "Pull Request Branch Names:"
          echo "---------------------------"
          
          for pr in $(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls" | jq -r '.[].html_url'); do
            echo "- $pr"
          done
          echo "---------------------"
          echo "echo:"
          echo $(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls" | jq -r '.[].head.ref')
          echo lets see done

        