name: DEV AWS Deploy

env:
  ENV: airflow-test

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
  AWS_DEFAULT_REGION: us-east-1

  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

  SHARED_REPO_NAME: EasyKnockOrg/devops-shared-library
  SHARED_REPO_NAME_SSH: git@github.com:EasyKnockOrg/devops-shared-library.git
  SHARED_REPO_BRANCH: master

  AWS_BUCKET_NAME: ek1-app-airflow-test
  AWS_AIRFLOW_ENV: ek1-air-airflow-test

  EKS_CLUSTER_NAME: ek1-eks-airflow-test
  K8S_ENV: tools
  K8S_PROJECT: airflow
  K8S_NAMESPACE: default

  K8S_ECR_SHORT01: ek1-air-image01
  DOCKER_FILE01: Dockerfile-lead-score
  K8S_ECR_SHORT02: ek1-air-address-standardization
  DOCKER_FILE02: Dockerfile-address-standardization
  K8S_ECR_SHORT03: ek1-air-airtable-data
  DOCKER_FILE03: Dockerfile-airtable-data
  K8S_ECR_SHORT04: ek1-air-appfolio-address-standardization
  DOCKER_FILE04: Dockerfile-appfolio-address-standardization
  K8S_ECR_SHORT05: ek1-air-bing-data
  DOCKER_FILE05: Dockerfile-bing-data
  K8S_ECR_SHORT06: ek1-air-google-adwords
  DOCKER_FILE06: Dockerfile-google-adwords
  K8S_ECR_SHORT07: ek1-air-netsuite-data
  DOCKER_FILE07: Dockerfile-netsuite-data
  
on:
  workflow_dispatch:
  delete:
  push:
    branches: 
      - '**'
      # - '!develop'
      # - '!main'
      


  # pull_request:
  #   branches:
  #   - 'main'
    


jobs:

  
  Dags:
    name: 'Dags/Sync'

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_DEFAULT_REGION }}
        
      - name: sync to s3
        run: |
          echo github "${{toJson(github)}}" || true
          echo haha
          