name: Echo Push Diff Files

on:
  push:
    branches-ignore:
      - main

jobs:
  echo-push-diff-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Determine the pushed branch
        id: branch
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Echo push diff file names
        run: |
          echo "Push Diff Files:"
          echo "----------------"

          # Get the list of modified files in the latest push
          diff_files=$(git diff --name-only HEAD^..HEAD)

          # Check if the branch is not 'main' and if 'origin/main' is involved in the push
          if [ "${BRANCH_NAME}" != "main" ] && git log --oneline --format='%h' --grep='origin/main' | grep -q .; then
            echo "Files in the latest push on branch '${BRANCH_NAME}' with 'origin/main' involvement:"
            echo "$diff_files" | sed 's/^/  - /'
          else
            echo "No relevant changes in the latest push on branch '${BRANCH_NAME}'."
          fi
