name: Prod Deploy

env:
  JSON: ${{ toJSON(github) }}

on:
  workflow_dispatch:
  delete:
  push:
    branches: 
      - 'main'
      # - '!develop'
    #   - '!main'
      
  pull_request:
    types: [closed]
    branches:
    - '**'
    


jobs:
  Dags:
    name: 'Dags/Sync'

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: sync to s3
        run: |
          echo env.PARAMS_ENTERED ${{ env.PARAMS_ENTERED }}
          echo github.ref_name  ${{ github.ref_name }}
          echo prod branch name ${{ github.event.ref }}
          echo github "${{env.JSON}}" || true
          echo github ${{github}}

          